version: '3.8'
services:
  client:
    stdin_open: true
    tty: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /client/node_modules
      - ./client:/client
    ports:
      - 3000:3000
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    env_file:
      - ./server/.env
    volumes:
      - ./server:/server
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - "MYSQL_DATABASE=blog"
      - "MYSQL_USER=blog"
      - "MYSQL_PASSWORD=local@123"
      - "MYSQL_ROOT_PASSWORD=local@123"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 2s
      retries: 5
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - client
      - server
    restart: always
    ports:
      - 5001:80
