version: '3.8'
services:
  client:
    stdin_open: true
    tty: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev 
    volumes:
      - /client/node_modules
      - ./client:/client
    ports:
      - 3000:3000
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - client
    restart: always
    ports:
      - 5001:80