/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from "next";
import "./globals.scss";
import ThemeProvider from "@/providers/Theme.provider";
import AppErrorBoundary from "@/components/error/ErrorBoundry";
import ApplicationLayout from "@/components/layout/Application/ApplicationLayout";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />

                <link
                    href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:ital,wght@0,200..900;1,200..900&display=swap"
                    rel="stylesheet"
                />
                 <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700&display=swap" rel="stylesheet" />
            </head>
            <body>
                <AppErrorBoundary>
                    <ThemeProvider>
                        <ApplicationLayout>{children}</ApplicationLayout>
                    </ThemeProvider>
                </AppErrorBoundary>
            </body>
        </html>
    );
}
